/* Generated by AN DISI Unibo */ 
package it.unibo.parkmanagerservice

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Parkmanagerservice ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "moveToHome"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		 var POSTILIBERI = 6
				var robotLibero = true
				var outdoorLibera = true
				var indoorLibera = true	
				var PROGRESSIVO = 0	
				var STATO = "IDLE"
				lateinit var outSonarActor : ActorBasic
				
				val mapname     = "mappaParcheggio"  		 
				var Myself      = myself   
				var CurrentPlannedMove = "" 
				var RobotType     = "" 
				var matriceParcheggi = arrayOf(intArrayOf(0,0),intArrayOf(0,0),intArrayOf(0,0))
		
		return { //this:ActionBasciFsm
				state("moveToHome") { //this:State
					action { //it:State
						outSonarActor     = sysUtil.getActor("outsonar")!! 
						unibo.robot.robotSupport.create(myself ,"basicrobotConfig.json" )
						 RobotType = unibo.robot.robotSupport.robotKind  
						updateResourceRep( "basicrobot(start)"  
						)
						itunibo.planner.plannerUtil.initAI(  )
						println("&&&  trolley loads the parking map from the given file ...")
						itunibo.planner.plannerUtil.loadRoomMap( "$mapname"  )
						itunibo.planner.plannerUtil.showMap(  )
						itunibo.planner.plannerUtil.showCurrentRobotState(  )
						pathexecutil.register( Myself  )
						forward("goto", "goto(home)" ,"parkmanagerservice" ) 
					}
					 transition(edgeName="t09",targetState="acceptin",cond=whenEvent("acceptin"))
					transition(edgeName="t010",targetState="goto",cond=whenDispatch("goto"))
					transition(edgeName="t011",targetState="acceptout",cond=whenRequest("acceptout"))
					transition(edgeName="t012",targetState="uscitalibera",cond=whenEvent("uscitalibera"))
					transition(edgeName="t013",targetState="timeout",cond=whenEvent("timeout"))
					transition(edgeName="t014",targetState="stopped",cond=whenEvent("stop"))
				}	 
				state("stopped") { //this:State
					action { //it:State
						if(  STATO.equals("IDLE") || STATO.equals("WORKING")  
						 ){ STATO = "STOP"  
						forward("cambiostato", "cambiostato($STATO)" ,"managerservice" ) 
						}
						println("IL ROBOT è STATO FERMATO")
					}
					 transition(edgeName="t015",targetState="start",cond=whenEvent("start"))
				}	 
				state("start") { //this:State
					action { //it:State
						if(  STATO.equals("STOP")  
						 ){ STATO = "WORKING"  
						forward("cambiostato", "cambiostato($STATO)" ,"managerservice" ) 
						}
						println("RIPARTO")
					}
					 transition(edgeName="t016",targetState="acceptin",cond=whenEvent("acceptin"))
					transition(edgeName="t017",targetState="goto",cond=whenDispatch("goto"))
					transition(edgeName="t018",targetState="informin",cond=whenDispatch("informin"))
					transition(edgeName="t019",targetState="movetoin",cond=whenRequest("carenter"))
					transition(edgeName="t020",targetState="acceptout",cond=whenRequest("acceptout"))
					transition(edgeName="t021",targetState="uscitalibera",cond=whenEvent("uscitalibera"))
					transition(edgeName="t022",targetState="timeout",cond=whenEvent("timeout"))
					transition(edgeName="t023",targetState="movetoslotout",cond=whenDispatch("movetoslotout"))
					transition(edgeName="t024",targetState="findslot",cond=whenDispatch("findslot"))
				}	 
				state("acceptin") { //this:State
					action { //it:State
						if(  STATO.equals("IDLE") || STATO.equals("STOP")  
						 ){ STATO = "WORKING"  
						forward("cambiostato", "cambiostato($STATO)" ,"managerservice" ) 
						}
						if(  indoorLibera  
						 ){println("Vado in informin")
						forward("informin", "informin" ,"parkmanagerservice" ) 
						}
						else
						 {emit("acceptin", "acceptin" ) 
						 }
					}
					 transition(edgeName="t025",targetState="stopped",cond=whenEvent("stop"))
					transition(edgeName="t026",targetState="informin",cond=whenDispatch("informin"))
					transition(edgeName="t027",targetState="acceptin",cond=whenEvent("acceptin"))
					transition(edgeName="t028",targetState="uscitalibera",cond=whenEvent("uscitalibera"))
					transition(edgeName="t029",targetState="timeout",cond=whenEvent("timeout"))
				}	 
				state("informin") { //this:State
					action { //it:State
						forward("slotsnum", "slotsnum($POSTILIBERI)" ,"cliente" ) 
					}
					 transition(edgeName="t030",targetState="stopped",cond=whenEvent("stop"))
					transition(edgeName="t031",targetState="movetoin",cond=whenRequest("carenter"))
					transition(edgeName="t032",targetState="uscitalibera",cond=whenEvent("uscitalibera"))
					transition(edgeName="t033",targetState="timeout",cond=whenEvent("timeout"))
				}	 
				state("movetoin") { //this:State
					action { //it:State
						 robotLibero=false 
									indoorLibera=false	
									POSTILIBERI --
						updateResourceRep( "POSTILIBERI"  
						)
						println("Robot move to in")
						itunibo.planner.plannerUtil.planForGoal( "5", "0"  )
						  CurrentPlannedMove = itunibo.planner.plannerUtil.getNextPlannedMove() 
						
						  		 	while(CurrentPlannedMove.length>0){
						  		 		println("MOSSa $CurrentPlannedMove")
						  		 		itunibo.planner.plannerUtil.updateMap("$CurrentPlannedMove")
						if(  CurrentPlannedMove.equals("w") || CurrentPlannedMove.equals("s")  
						 ){unibo.robot.robotSupport.move( "$CurrentPlannedMove"  )
						delay(400) 
						unibo.robot.robotSupport.move( "h"  )
						}
						else
						 {unibo.robot.robotSupport.move( "$CurrentPlannedMove"  )
						 }
								
						  		 		CurrentPlannedMove = itunibo.planner.plannerUtil.getNextPlannedMove()
						  		 	}
						  		 	
						  		 	
						println("Robot AT INDOOR")
					}
					 transition( edgeName="goto",targetState="receipt", cond=doswitch() )
				}	 
				state("receipt") { //this:State
					action { //it:State
						answer("carenter", "receipt", "receipt($PROGRESSIVO)"   )  
						forward("goto", "goto($PROGRESSIVO)" ,"parkmanagerservice" ) 
						forward("parcheggioOccupato", "parcheggioOccupato($PROGRESSIVO)" ,"managerservice" ) 
						 PROGRESSIVO++  
						updateResourceRep( "$PROGRESSIVO"  
						)
					}
					 transition(edgeName="t034",targetState="stopped",cond=whenEvent("stop"))
					transition(edgeName="t035",targetState="goto",cond=whenDispatch("goto"))
					transition(edgeName="t036",targetState="uscitalibera",cond=whenEvent("uscitalibera"))
				}	 
				state("goto") { //this:State
					action { //it:State
						 robotLibero=false  
						if( checkMsgContent( Term.createTerm("goto(V)"), Term.createTerm("goto(ST)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 var ST = payloadArg(0) 
												println(ST)
								if(  ST.equals("home")  
								 ){if(  STATO.equals("WORKING") || STATO.equals("STOP")  
								 ){ STATO = "IDLE"  
								forward("cambiostato", "cambiostato($STATO)" ,"managerservice" ) 
								}
								println("Ric. gotohome")
								println("ROBOT at HOME")
								 robotLibero=true  
								}
								else
								 { var POS = payloadArg(0)  
								 println("ROBOT $ST move to $POS")
								  indoorLibera=true  
								 forward("goto", "goto(home)" ,"parkmanagerservice" ) 
								 }
						}
					}
					 transition(edgeName="t037",targetState="stopped",cond=whenEvent("stop"))
					transition(edgeName="t038",targetState="goto",cond=whenDispatch("goto"))
					transition(edgeName="t039",targetState="acceptin",cond=whenEvent("acceptin"))
					transition(edgeName="t040",targetState="acceptout",cond=whenRequest("acceptout"))
					transition(edgeName="t041",targetState="movetoout",cond=whenDispatch("movetoout"))
					transition(edgeName="t042",targetState="uscitalibera",cond=whenEvent("uscitalibera"))
					transition(edgeName="t043",targetState="timeout",cond=whenEvent("timeout"))
				}	 
				state("movetoslotout") { //this:State
					action { //it:State
						 robotLibero=false  
						if( checkMsgContent( Term.createTerm("movetoslotout(V)"), Term.createTerm("movetoslotout(POS)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 var POS = payloadArg(0)  
								println("ROBOT move to $POS")
								delay(2000) 
						}
					}
					 transition( edgeName="goto",targetState="movetoout", cond=doswitch() )
				}	 
				state("movetoout") { //this:State
					action { //it:State
						println("movetoout")
						 outdoorLibera = false  
						delay(2000) 
						forward("goto", "goto(home)" ,"parkmanagerservice" ) 
						emit("arrivoauto", "arrivoauto" ) 
					}
					 transition(edgeName="t044",targetState="stopped",cond=whenEvent("stop"))
					transition(edgeName="t045",targetState="goto",cond=whenDispatch("goto"))
					transition(edgeName="t046",targetState="timeout",cond=whenEvent("timeout"))
				}	 
				state("acceptout") { //this:State
					action { //it:State
						println("acceptout")
						if(  STATO.equals("IDLE") || STATO.equals("STOP")  
						 ){ STATO = "WORKING"  
						forward("cambiostato", "cambiostato($STATO)" ,"managerservice" ) 
						}
						if(  outdoorLibera  
						 ){if( checkMsgContent( Term.createTerm("acceptout(V)"), Term.createTerm("acceptout(TOKENID)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								  var T = payloadArg(0) 
													POSTILIBERI ++
													
								updateResourceRep( "POSTILIBERI"  
								)
								forward("findslot", "findslot($T)" ,"parkmanagerservice" ) 
								forward("parcheggioLibero", "parcheggioLibero($T)" ,"managerservice" ) 
								println("Slot $T")
						}
						answer("acceptout", "response", "response(true)"   )  
						}
						else
						 {answer("acceptout", "response", "response(false)"   )  
						 }
					}
					 transition(edgeName="t047",targetState="stopped",cond=whenEvent("stop"))
					transition(edgeName="t048",targetState="findslot",cond=whenDispatch("findslot"))
				}	 
				state("findslot") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("findslot(V)"), Term.createTerm("findslot(TOKEN)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 var TOKEN = payloadArg(0)  
								println("findslot")
								forward("movetoslotout", "movetoslotout($TOKEN)" ,"parkmanagerservice" ) 
						}
					}
					 transition(edgeName="t049",targetState="stopped",cond=whenEvent("stop"))
					transition(edgeName="t050",targetState="movetoslotout",cond=whenDispatch("movetoslotout"))
				}	 
				state("uscitalibera") { //this:State
					action { //it:State
						 outdoorLibera = true  
						updateResourceRep( "$outdoorLibera"  
						)
						forward("uscitalibera1", "uscitalibera1(V)" ,"managerservice" ) 
					}
					 transition(edgeName="t051",targetState="stopped",cond=whenEvent("stop"))
					transition(edgeName="t052",targetState="acceptin",cond=whenEvent("acceptin"))
					transition(edgeName="t053",targetState="goto",cond=whenDispatch("goto"))
					transition(edgeName="t054",targetState="informin",cond=whenDispatch("informin"))
					transition(edgeName="t055",targetState="movetoin",cond=whenRequest("carenter"))
				}	 
				state("timeout") { //this:State
					action { //it:State
						println("ALARM")
						forward("timeout1", "timeout1(V)" ,"managerservice" ) 
					}
					 transition(edgeName="t056",targetState="stopped",cond=whenEvent("stop"))
					transition(edgeName="t057",targetState="acceptin",cond=whenEvent("acceptin"))
					transition(edgeName="t058",targetState="goto",cond=whenDispatch("goto"))
					transition(edgeName="t059",targetState="informin",cond=whenDispatch("informin"))
					transition(edgeName="t060",targetState="acceptin",cond=whenEvent("acceptin"))
					transition(edgeName="t061",targetState="movetoin",cond=whenRequest("carenter"))
				}	 
			}
		}
}
