/* Generated by AN DISI Unibo */ 
package parcheggio
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	println("CIAO")
}